README.md, src/main/java/com/webank/webase/node/mgr/scheduler/PullBlockInfoTask.java, src/main/resources/application.yml
change sleep time of pull block
=> change sleep time of pull block

script/webase-dml.sql, src/main/java/com/webank/webase/node/mgr/account/AccountController.java, src/main/java/com/webank/webase/node/mgr/base/config/SecurityConfig.java, src/main/java/com/webank/webase/node/mgr/base/exception/ExceptionsHandler.java, src/main/java/com/webank/webase/node/mgr/base/properties/ConstantProperties.java, src/main/java/com/webank/webase/node/mgr/contract/ContractController.java, src/main/java/com/webank/webase/node/mgr/node/NodeController.java, src/main/java/com/webank/webase/node/mgr/role/RoleController.java, src/main/java/com/webank/webase/node/mgr/user/UserController.java, src/main/resources/application.yml
Improve interface access control
=> Improve interface access control

src/main/java/com/webank/webase/node/mgr/contract/ContractController.java, src/main/java/com/webank/webase/node/mgr/contract/ContractService.java, src/main/java/com/webank/webase/node/mgr/monitor/MonitorService.java
update monitor info after contractInfo save
=> update monitor info after contractInfo save

interfaces.md, src/main/java/com/webank/webase/node/mgr/base/properties/ConstantProperties.java, src/main/java/com/webank/webase/node/mgr/scheduler/TransMonitorTask.java, src/main/java/com/webank/webase/node/mgr/transaction/TransHashMapper.java, src/main/java/com/webank/webase/node/mgr/transaction/TransHashService.java, src/main/resources/application.yml, src/main/resources/mapper/BlockMapper.xml, src/main/resources/mapper/TransHashMapper.xml, src/main/resources/mapper/UserTransMonitorMapper.xml
1、support config max_unusual_count of monitor
2、add limit to delete db info
=> 1、support config max_unusual_count of monitor

src/main/java/com/webank/webase/node/mgr/contract/ContractService.java
fix:New contract interface error
=> fix:New contract interface error

script/webase-dml.sql, src/main/java/com/webank/webase/node/mgr/account/AccountController.java, src/main/java/com/webank/webase/node/mgr/account/AccountService.java, src/main/java/com/webank/webase/node/mgr/base/properties/ConstantProperties.java, src/main/java/com/webank/webase/node/mgr/base/tools/NodeMgrTools.java, src/main/java/com/webank/webase/node/mgr/base/tools/TokenImgGenerator.java, src/main/java/com/webank/webase/node/mgr/front/FrontService.java, src/main/java/com/webank/webase/node/mgr/frontinterface/FrontRestTools.java, src/main/java/com/webank/webase/node/mgr/monitor/MonitorService.java, src/main/java/com/webank/webase/node/mgr/node/NodeService.java, src/main/java/com/webank/webase/node/mgr/scheduler/PullBlockInfoTask.java, src/main/java/com/webank/webase/node/mgr/scheduler/TransMonitorTask.java, src/main/java/com/webank/webase/node/mgr/user/UserService.java, src/main/java/com/webank/webase/node/mgr/user/entity/BindUserInputParam.java, src/main/java/com/webank/webase/node/mgr/user/entity/NewUserInputParam.java, src/main/resources/application.yml, src/test/java/node/mgr/test/front/FrontControllerTest.java, src/test/java/node/mgr/test/frontInterface/FrontServiceTest.java
1、 handler InterruptedException
2、 config frontIp list
3、 init cns method
=> 1、 handler InterruptedException

src/main/java/com/webank/webase/node/mgr/base/config/SecurityConfig.java, src/main/java/com/webank/webase/node/mgr/contract/ContractService.java, src/main/java/com/webank/webase/node/mgr/frontinterface/FrontRestTools.java, src/main/java/com/webank/webase/node/mgr/user/UserController.java, src/main/java/com/webank/webase/node/mgr/user/UserMapper.java, src/main/java/com/webank/webase/node/mgr/user/UserService.java, src/main/resources/mapper/UserMapper.xml
fix: User attribute removes username and group（webase-sign）
=> fix: User attribute removes username and group（webase-sign）

src/main/java/com/webank/webase/node/mgr/base/config/SecurityConfig.java, src/main/java/com/webank/webase/node/mgr/base/properties/ConstantProperties.java, src/main/java/com/webank/webase/node/mgr/contract/ContractService.java, src/main/java/com/webank/webase/node/mgr/monitor/MonitorService.java, src/main/java/com/webank/webase/node/mgr/scheduler/PullBlockInfoTask.java, src/main/java/com/webank/webase/node/mgr/scheduler/SchedulerService.java, src/main/java/com/webank/webase/node/mgr/scheduler/TransMonitorTask.java, src/main/java/com/webank/webase/node/mgr/security/AccountDetailsService.java, src/main/java/com/webank/webase/node/mgr/security/LoginFailHandler.java, src/main/resources/application.yml, src/main/resources/mapper/TransHashMapper.xml
1、 fix:Distinguish account errors and password errors
2、 fix:Dealing with the problem that the audit speed can't keep up
=> 1、 fix:Distinguish account errors and password errors

README.md, install_FAQ.md, interfaces.md, src/main/java/com/webank/webase/node/mgr/base/code/ConstantCode.java, src/main/java/com/webank/webase/node/mgr/base/properties/ConstantProperties.java, src/main/java/com/webank/webase/node/mgr/block/BlockService.java, src/main/java/com/webank/webase/node/mgr/frontinterface/FrontRestTools.java, src/main/java/com/webank/webase/node/mgr/monitor/MonitorService.java, src/main/java/com/webank/webase/node/mgr/monitor/MonitorTransactionService.java, src/main/java/com/webank/webase/node/mgr/scheduler/PullBlockInfoTask.java, src/main/java/com/webank/webase/node/mgr/scheduler/SchedulerService.java, src/main/java/com/webank/webase/node/mgr/scheduler/TransMonitorTask.java, src/main/resources/application.yml, src/main/resources/mapper/TransHashMapper.xml, src/main/resources/mapper/UserTransMonitorMapper.xml
1、 fix:CountDownLatch in metho
2、fix: monitorTask:addFixedDelayTask -> addFixedRateTask
=> 1、 fix:CountDownLatch in method

install_FAQ.md
=> update: 10.0.0.52 -> 127.0.01

src/main/java/com/webank/webase/node/mgr/group/GroupService.java
=> fix: Failed to sync new group

src/main/java/com/webank/webase/node/mgr/monitor/MonitorService.java, src/main/java/com/webank/webase/node/mgr/user/UserService.java
fix: Cyclic dependence exception
=> fix: Cyclic dependence exception

src/main/resources/mapper/FrontMapper.xml, src/main/resources/mapper/UserTransMonitorMapper.xml
=> support mysql5.7+

src/main/java/com/webank/webase/node/mgr/security/customizeAuth/TokenAuthenticationProvider.java
=> fix:update access control

src/main/java/com/webank/webase/node/mgr/base/filter/ValidateCodeFilter.java
Invalid verification code cannot be logged in
=> fix: Invalid verification code cannot be logged in

src/main/java/com/webank/webase/node/mgr/user/UserService.java
Distinguish public keys by group
=> fix: Distinguish public keys by group

src/main/java/com/webank/webase/node/mgr/cert/CertController.java, src/main/java/com/webank/webase/node/mgr/cert/CertService.java, src/main/java/com/webank/webase/node/mgr/frontinterface/FrontInterfaceService.java
- seperate pull front's cert with getAllCertFromDb, avoiding stack overflow
- fix isPullFrontCertDone always true problem
=> Fix pull front's certs

src/main/java/com/webank/webase/node/mgr/cert/CertService.java, src/main/java/com/webank/webase/node/mgr/precompiled/PrecompiledService.java, src/main/java/com/webank/webase/node/mgr/precompiled/permission/PermissionManageService.java, src/main/java/com/webank/webase/node/mgr/precompiled/sysconf/PrecompiledSysConfigService.java
adjust code style according to Sider PMD code rules:
ex:
```
if(certType.equals("node")) 
=>
if("node".equals(certType)) 
or =>
if(CertTools.TYPE_NODE.equals(certType)) 
```
avoiding NullPointerException
=> Add logger & adjust code

src/main/java/com/webank/webase/node/mgr/cert/CertController.java, src/main/java/com/webank/webase/node/mgr/cert/CertService.java, src/main/java/com/webank/webase/node/mgr/cert/CertTools.java, src/main/java/com/webank/webase/node/mgr/precompiled/PrecompiledController.java, src/main/java/com/webank/webase/node/mgr/precompiled/PrecompiledService.java, src/main/java/com/webank/webase/node/mgr/precompiled/permission/PermissionManageController.java, src/main/java/com/webank/webase/node/mgr/precompiled/permission/PermissionManageService.java, src/main/java/com/webank/webase/node/mgr/precompiled/sysconf/PrecompiledSysConfigController.java, src/main/java/com/webank/webase/node/mgr/precompiled/sysconf/PrecompiledSysConfigService.java
- adjust code style, ex: optimize try-catch(inputstream) modules;
- add log.info in controller with time duration in controller;
- add log.debug in service for debugging;
- add log.error to mark exception;
=> add logger & adjust code style

src/main/java/com/webank/webase/node/mgr/alert/task/NodeStatusMonitorTask.java, src/main/java/com/webank/webase/node/mgr/cert/CertService.java, src/main/java/com/webank/webase/node/mgr/front/FrontService.java, src/main/java/com/webank/webase/node/mgr/frontinterface/FrontInterfaceService.java, src/main/java/com/webank/webase/node/mgr/frontinterface/FrontRestTools.java, src/main/java/com/webank/webase/node/mgr/group/GroupService.java, src/main/java/com/webank/webase/node/mgr/node/NodeMapper.java, src/main/java/com/webank/webase/node/mgr/node/NodeParam.java, src/main/java/com/webank/webase/node/mgr/node/NodeService.java, src/main/java/com/webank/webase/node/mgr/scheduler/PullBlockInfoTask.java, src/main/resources/application.yml, src/test/java/node/mgr/test/node/NodeControllerTest.java
- add alert log modules and apis
- add disconnected sealer/observer in NodeList as abonormal nodes
=> Add alert logs && fix disconnected node alert problem

src/main/java/com/webank/webase/node/mgr/alert/log/AlertLogController.java, src/main/java/com/webank/webase/node/mgr/alert/log/AlertLogMapper.java, src/main/java/com/webank/webase/node/mgr/alert/log/AlertLogService.java, src/main/java/com/webank/webase/node/mgr/alert/log/entity/ReqLogListParam.java, src/main/java/com/webank/webase/node/mgr/alert/log/entity/ReqLogParam.java, src/main/resources/mapper/AlertLogMapper.xml
- Add pagition in alert log 
- rm alert log's post
- add license
=> Add pagition in alert log api

script/webase-dml.sql, src/main/java/com/webank/webase/node/mgr/alert/mail/MailService.java, src/main/java/com/webank/webase/node/mgr/alert/rule/AlertRuleController.java, src/main/java/com/webank/webase/node/mgr/alert/rule/AlertRuleService.java
- Del default email of AlertRule;
- check userList's empty in alert rule toggle api
=> Del default email of AlertRule

src/main/java/com/webank/webase/node/mgr/group/GroupService.java, src/test/java/node/mgr/test/frontInterface/FrontServiceTest.java, src/test/java/node/mgr/test/frontgroupmap/FrontGroupMapServiceTest.java
- deprecate refresh front in startGroup
- add test
=> deprecate refresh front in startGroup

src/main/java/com/webank/webase/node/mgr/base/filter/AbstractAuthenticationFilter.java, src/main/java/com/webank/webase/node/mgr/base/tools/NodeMgrTools.java
change "Authorization" to "AuthorizationToken"
=> Change login authentication request header

build.gradle, src/main/java/com/webank/webase/node/mgr/front/entity/TransactionParam.java, src/main/java/com/webank/webase/node/mgr/frontinterface/FrontRestTools.java, src/main/java/com/webank/webase/node/mgr/precompiled/PrecompiledService.java, src/main/java/com/webank/webase/node/mgr/precompiled/permission/PermissionManageService.java, src/main/java/com/webank/webase/node/mgr/precompiled/sysconf/PrecompiledSysConfigService.java
- precompiled useAes default true 
- fix overloaded function
=> Bugfix precompiled useAes default true & fix overloaded function

src/main/java/com/webank/webase/node/mgr/base/exception/NodeMgrException.java, src/main/java/com/webank/webase/node/mgr/frontgroupmap/FrontGroupMapMapper.java, src/main/java/com/webank/webase/node/mgr/frontgroupmap/FrontGroupMapService.java, src/main/java/com/webank/webase/node/mgr/frontinterface/FrontInterfaceService.java, src/main/java/com/webank/webase/node/mgr/frontinterface/FrontRestTools.java, src/main/java/com/webank/webase/node/mgr/group/GroupService.java, src/main/resources/mapper/FrontGroupMapMapper.xml
remove invalid data on tb_front_group_map
=> remove invalid data on tb_front_group_map

src/main/java/com/webank/webase/node/mgr/base/exception/NodeMgrException.java, src/main/java/com/webank/webase/node/mgr/frontinterface/FrontRestTools.java
=> match checkStyle.xml

src/main/java/com/webank/webase/node/mgr/base/code/ConstantCode.java, src/main/java/com/webank/webase/node/mgr/contract/ContractController.java, src/main/java/com/webank/webase/node/mgr/contract/ContractService.java, src/main/java/com/webank/webase/node/mgr/frontinterface/FrontInterfaceService.java, src/main/java/com/webank/webase/node/mgr/group/GroupService.java, src/main/java/com/webank/webase/node/mgr/precompiled/permission/PermissionManageController.java, src/main/java/com/webank/webase/node/mgr/precompiled/permission/PermissionManageService.java
- add null genesisi block warn log
- add deploy permission check
- add zero address validation
=> add validation of deploy

src/main/java/com/webank/webase/node/mgr/base/code/ConstantCode.java, src/main/java/com/webank/webase/node/mgr/frontinterface/FrontRestTools.java, src/main/java/com/webank/webase/node/mgr/group/GroupService.java, src/main/resources/mapper/GroupMapper.xml
- fix remove group auto 
- optimize check dirty data from all front
- fix group modify time null
=> fix remove group auto &  optimize check dirty data from all front

build.gradle
Reverts WeBankFinTech/WeBASE-Node-Manager#202
=> Revert "upgrade web3sdk to 2.4.2"

src/main/java/com/webank/webase/node/mgr/chain/ChainService.java, src/main/java/com/webank/webase/node/mgr/deploy/controller/DeployController.java, src/main/java/com/webank/webase/node/mgr/deploy/service/DeployShellService.java, src/main/java/com/webank/webase/node/mgr/deploy/service/HostService.java, src/main/java/com/webank/webase/node/mgr/front/FrontService.java, src/main/java/com/webank/webase/node/mgr/frontgroupmap/FrontGroupMapService.java, src/main/java/com/webank/webase/node/mgr/group/GroupService.java, src/main/resources/templates/node/front-application-yml.tpl
1. add monitor
2. delete tmp file when deploy chain failed
=> 1.4.0 visual deploy

src/main/java/com/webank/webase/node/mgr/base/config/ThreadPoolConfig.java, src/main/java/com/webank/webase/node/mgr/deploy/service/HostService.java
1. change deploy pool size to 20
=> update deploy thread pool size

src/main/java/com/webank/webase/node/mgr/base/tools/ThymeleafUtil.java, src/main/resources/application.yml
1. set deployType to 0 in applicatin.yml
2. add ThymeleafUtil generate log
=> add ThymeleafUtil generate log

src/main/java/com/webank/webase/node/mgr/deploy/service/DeployShellService.java
=> add quote on path

src/main/java/com/webank/webase/node/mgr/chain/ChainService.java, src/main/java/com/webank/webase/node/mgr/group/GroupService.java, src/main/java/com/webank/webase/node/mgr/scheduler/ResetGroupListTask.java
=> change task condition

Changelog.md
1. add version of api front/find
=> v1.4.0 update change log

script/webase-ddl.sql, src/main/java/com/webank/webase/node/mgr/group/GroupService.java, src/main/java/com/webank/webase/node/mgr/group/entity/TbGroup.java
- fix `null` convert to `int` error
=> fix dynamic group manager join group 

script/deploy/host_check.sh, script/deploy/host_docker_check.sh, src/main/java/com/webank/webase/node/mgr/base/code/ConstantCode.java, src/main/java/com/webank/webase/node/mgr/base/enums/DataStatus.java, src/main/java/com/webank/webase/node/mgr/base/properties/ConstantProperties.java, src/main/java/com/webank/webase/node/mgr/base/tools/ProgressTools.java, src/main/java/com/webank/webase/node/mgr/base/tools/ThymeleafUtil.java, src/main/java/com/webank/webase/node/mgr/chain/ChainService.java, src/main/java/com/webank/webase/node/mgr/deploy/controller/DeployController.java, src/main/java/com/webank/webase/node/mgr/deploy/service/AnsibleService.java, src/main/java/com/webank/webase/node/mgr/deploy/service/DeployService.java, src/main/java/com/webank/webase/node/mgr/deploy/service/DockerCommandService.java, src/main/java/com/webank/webase/node/mgr/deploy/service/HostService.java, src/main/java/com/webank/webase/node/mgr/deploy/service/NodeAsyncService.java, src/main/java/com/webank/webase/node/mgr/front/FrontService.java, src/main/java/com/webank/webase/node/mgr/frontgroupmap/FrontGroupMapCache.java, src/main/java/com/webank/webase/node/mgr/frontgroupmap/FrontGroupMapService.java, src/main/java/com/webank/webase/node/mgr/frontinterface/FrontInterfaceService.java, src/main/java/com/webank/webase/node/mgr/frontinterface/FrontRestTools.java, src/main/java/com/webank/webase/node/mgr/node/NodeService.java, src/main/java/com/webank/webase/node/mgr/performance/PerformanceService.java, src/main/resources/application.yml, src/main/resources/mapper/FrontGroupMapMapper.xml
- fix stop/start node wait time 
- add log 
- fix deadlock when delete 
- fix host not exist when deploy 
- fix request sealer list when new front group map
=> fix stop/start node wait time & fix host not exist when deploy & fix new front

script/webase-ddl.sql, src/main/java/com/webank/webase/node/mgr/deploy/mapper/TbHostMapper.java, src/main/java/com/webank/webase/node/mgr/deploy/service/AnsibleService.java, src/main/java/com/webank/webase/node/mgr/deploy/service/HostService.java, src/main/java/com/webank/webase/node/mgr/front/FrontController.java, src/main/java/com/webank/webase/node/mgr/front/FrontService.java, src/main/java/com/webank/webase/node/mgr/front/entity/FrontParam.java, src/main/java/com/webank/webase/node/mgr/frontgroupmap/FrontGroupMapCache.java, src/main/java/com/webank/webase/node/mgr/frontgroupmap/FrontGroupMapService.java, src/main/java/com/webank/webase/node/mgr/frontinterface/FrontRestTools.java, src/main/java/com/webank/webase/node/mgr/group/GroupService.java, src/main/java/com/webank/webase/node/mgr/monitor/MonitorService.java, src/main/java/com/webank/webase/node/mgr/node/NodeMapper.java, src/main/java/com/webank/webase/node/mgr/node/NodeService.java, src/main/java/com/webank/webase/node/mgr/scheduler/ResetGroupListTask.java, src/main/java/com/webank/webase/node/mgr/user/UserService.java, src/main/resources/mapper/FrontMapper.xml, src/main/resources/mapper/NodeMapper.xml, src/main/resources/mapper/UserMapper.xml
- add status when find front 
-  fix updateHost status
- add user unique
=> optimize resetGroupList & use local highest height etc.

src/main/java/com/webank/webase/node/mgr/contract/ContractService.java
=> 修复编译合约时生成脏数据问题

src/main/java/com/webank/webase/node/mgr/base/code/ConstantCode.java, src/main/java/com/webank/webase/node/mgr/frontinterface/FrontInterfaceService.java, src/main/java/com/webank/webase/node/mgr/frontinterface/FrontRestTools.java, src/main/java/com/webank/webase/node/mgr/transaction/TransHashController.java, src/main/java/com/webank/webase/node/mgr/transaction/TransHashService.java, src/main/java/com/webank/webase/node/mgr/transaction/entity/ReqSignMessage.java, src/main/java/com/webank/webase/node/mgr/user/UserController.java, src/main/java/com/webank/webase/node/mgr/user/UserService.java, src/main/java/com/webank/webase/node/mgr/user/entity/KeyPair.java
开发者账号导出私钥权限放开,完善合约工具，国密的hash，签名等工具
=> 开发者账号导出私钥权限放开,完善合约工具，国密的hash，签名等工具

script/webase-ddl.sql, src/main/java/com/webank/webase/node/mgr/config/properties/ConstantProperties.java, src/main/java/com/webank/webase/node/mgr/lock/DbWeLock.java, src/main/java/com/webank/webase/node/mgr/lock/LockMapper.java, src/main/java/com/webank/webase/node/mgr/lock/WeLock.java, src/main/java/com/webank/webase/node/mgr/lock/entity/TbLock.java, src/main/java/com/webank/webase/node/mgr/lock/service/LockService.java, src/main/java/com/webank/webase/node/mgr/scheduler/AppStatusCheckTask.java, src/main/java/com/webank/webase/node/mgr/scheduler/DeleteInfoTask.java, src/main/java/com/webank/webase/node/mgr/scheduler/PullBlockTransTask.java, src/main/java/com/webank/webase/node/mgr/scheduler/ResetGroupListTask.java, src/main/java/com/webank/webase/node/mgr/scheduler/StatisticsTransdailyTask.java, src/main/java/com/webank/webase/node/mgr/scheduler/TransMonitorTask.java, src/main/resources/application.yml, src/main/resources/mapper/LockMapper.xml, src/main/resources/mapper/UserMapper.xml
=> webase task 7 

src/main/java/com/webank/webase/node/mgr/appintegration/AppIntegrationController.java, src/main/java/com/webank/webase/node/mgr/appintegration/api/AppIntegrationApi.java, src/main/java/com/webank/webase/node/mgr/config/properties/ConstantProperties.java, src/main/java/com/webank/webase/node/mgr/front/frontinterface/FrontInterfaceService.java, src/main/resources/application.yml
=> feat:# add app managenment
